name: ✨ Feature Request
description: Suggest a new feature or enhancement for Zyeuté V3
title: "[FEATURE]: "
labels: ["feature"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: Alternative approaches could include...

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Feature
        - Enhancement
        - Performance Improvement
        - User Experience (UX)
        - Developer Experience (DX)
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (Blocking major functionality)
        - High (Significant improvement)
        - Medium (Nice to have)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe specific use cases for this feature.
      placeholder: |
        This feature would be useful when...
        Example scenario: ...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Design Ideas
      description: If applicable, add any mockups, wireframes, or design ideas.
      placeholder: Drag and drop images here or paste URLs

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: If you have technical implementation ideas, please share them.
      placeholder: |
        Potential implementation approach:
        - Technology: ...
        - Libraries: ...
        - API changes: ...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided sufficient detail for this feature request
          required: true
        - label: This feature aligns with the goals of Zyeuté V3
          required: true
